{
	"patcher" : 	{
		"fileversion" : 1,
		"appversion" : 		{
			"major" : 8,
			"minor" : 5,
			"revision" : 5,
			"architecture" : "x64",
			"modernui" : 1
		},
		"classnamespace" : "box",
		"rect" : [ 80.0, 60.0, 1000.0, 800.0 ],
		"bglocked" : 0,
		"openinpresentation" : 0,
		"default_fontsize" : 12.0,
		"default_fontface" : 0,
		"default_fontname" : "Arial",
		"gridonopen" : 1,
		"gridsize" : [ 15.0, 15.0 ],
		"gridsnaponopen" : 1,
		"objectsnaponopen" : 1,
		"statusbarvisible" : 2,
		"toolbarvisible" : 1,
		"lefttoolbarpinned" : 0,
		"toptoolbarpinned" : 0,
		"righttoolbarpinned" : 0,
		"bottomtoolbarpinned" : 0,
		"toolbars_unpinned" : 0,
		"tallnewobj" : 0,
		"boxanimatetime" : 200,
		"enablehscroll" : 1,
		"enablevscroll" : 1,
		"devicewidth" : 0.0,
		"description" : "",
		"digest" : "",
		"tags" : "",
		"style" : "",
		"subpatcher_template" : "",
		"assistshowspatchername" : 0,
		"boxes" : [
			{ "box" : { "id" : "obj-comment", "maxclass" : "comment", "numinlets" : 1, "numoutlets" : 0,
				"text" : "Chaotic feedback-network bass drum: logistic map drives rhythm + pitch, drum loudness feeds back into chaos parameter r. Click toggle to start.",
				"patching_rect" : [ 40.0, 5.0, 500.0, 30.0 ] } },
			{ "box" : { "id" : "obj-1", "maxclass" : "toggle", "numinlets" : 1, "numoutlets" : 1,
				"outlettype" : [ "int" ], "patching_rect" : [ 40.0, 45.0, 20.0, 20.0 ] } },
			{ "box" : { "id" : "obj-2", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "bang" ], "text" : "metro 60", "patching_rect" : [ 40.0, 90.0, 60.0, 22.0 ] } },
			{ "box" : { "id" : "obj-8", "maxclass" : "newobj", "numinlets" : 0, "numoutlets" : 1,
				"outlettype" : [ "bang" ], "text" : "loadbang", "patching_rect" : [ 160.0, 45.0, 70.0, 22.0 ] } },
			{ "box" : { "id" : "obj-9", "maxclass" : "message", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "" ], "text" : "0.37", "patching_rect" : [ 160.0, 90.0, 60.0, 22.0 ] } },
			{ "box" : { "id" : "obj-7", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "" ], "text" : "f", "patching_rect" : [ 40.0, 150.0, 40.0, 22.0 ] } },
			{ "box" : { "id" : "obj-xnum", "maxclass" : "flonum", "numinlets" : 1, "numoutlets" : 1,
				"outlettype" : [ "float" ], "patching_rect" : [ 100.0, 150.0, 60.0, 22.0 ] } },
			{ "box" : { "id" : "obj-11", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "" ], "text" : "> 0.55", "patching_rect" : [ 200.0, 150.0, 60.0, 22.0 ] } },
			{ "box" : { "id" : "obj-EXPR", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "" ], "text" : "expr $f2 * $f1 * (1 - $f1)", "patching_rect" : [ 320.0, 150.0, 220.0, 22.0 ] } },
			{ "box" : { "id" : "obj-12", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 2,
				"outlettype" : [ "bang", "" ], "text" : "sel 1", "patching_rect" : [ 200.0, 210.0, 40.0, 22.0 ] } },
			{ "box" : { "id" : "obj-fscale", "maxclass" : "newobj", "numinlets" : 5, "numoutlets" : 1,
				"outlettype" : [ "float" ], "text" : "scale 0. 1. 45. 95.", "patching_rect" : [ 40.0, 210.0, 130.0, 22.0 ] } },
			{ "box" : { "id" : "obj-fhold", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "" ], "text" : "f", "patching_rect" : [ 40.0, 270.0, 40.0, 22.0 ] } },
			{ "box" : { "id" : "obj-13", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 3,
				"outlettype" : [ "bang", "bang", "bang" ], "text" : "t b b b", "patching_rect" : [ 160.0, 270.0, 60.0, 22.0 ] } },
			{ "box" : { "id" : "obj-phasereset", "maxclass" : "message", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "" ], "text" : "0.", "patching_rect" : [ 260.0, 270.0, 40.0, 22.0 ] } },
			{ "box" : { "id" : "obj-ampmsg", "maxclass" : "message", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "" ], "text" : "1, 0 300 -0.3", "patching_rect" : [ 320.0, 270.0, 120.0, 22.0 ] } },
			{ "box" : { "id" : "obj-clickmsg", "maxclass" : "message", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "" ], "text" : "1, 0 8", "patching_rect" : [ 460.0, 270.0, 70.0, 22.0 ] } },
			{ "box" : { "id" : "obj-fhtf", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 2,
				"outlettype" : [ "float", "float" ], "text" : "t f f", "patching_rect" : [ 40.0, 320.0, 40.0, 22.0 ] } },
			{ "box" : { "id" : "obj-mul03", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "float" ], "text" : "* 0.3", "patching_rect" : [ 40.0, 370.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-packpitch", "maxclass" : "newobj", "numinlets" : 3, "numoutlets" : 1,
				"outlettype" : [ "" ], "text" : "pack 0. 70. -0.8", "patching_rect" : [ 40.0, 420.0, 100.0, 22.0 ] } },
			{ "box" : { "id" : "obj-pitchcurve", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "curve~", "patching_rect" : [ 160.0, 420.0, 60.0, 22.0 ] } },
			{ "box" : { "id" : "obj-fundcycle", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "cycle~", "patching_rect" : [ 160.0, 470.0, 60.0, 22.0 ] } },
			{ "box" : { "id" : "obj-ampcurve", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "curve~", "patching_rect" : [ 320.0, 320.0, 60.0, 22.0 ] } },
			{ "box" : { "id" : "obj-fundmult", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "*~", "patching_rect" : [ 160.0, 520.0, 40.0, 22.0 ] } },
			{ "box" : { "id" : "obj-clickenv", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "line~", "patching_rect" : [ 460.0, 320.0, 60.0, 22.0 ] } },
			{ "box" : { "id" : "obj-noise", "maxclass" : "newobj", "numinlets" : 0, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "noise~", "patching_rect" : [ 530.0, 320.0, 60.0, 22.0 ] } },
			{ "box" : { "id" : "obj-impulse", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "*~", "patching_rect" : [ 490.0, 370.0, 40.0, 22.0 ] } },
			{ "box" : { "id" : "obj-beaterfilt", "maxclass" : "newobj", "numinlets" : 3, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "lores~ 1800 0.2", "patching_rect" : [ 490.0, 420.0, 90.0, 22.0 ] } },
			{ "box" : { "id" : "obj-beatergain", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "*~ 0.25", "patching_rect" : [ 490.0, 470.0, 60.0, 22.0 ] } },
			{ "box" : { "id" : "obj-ratio1", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "float" ], "text" : "* 1.0", "patching_rect" : [ 620.0, 270.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-ratio2", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "float" ], "text" : "* 1.59", "patching_rect" : [ 680.0, 270.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-ratio3", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "float" ], "text" : "* 2.14", "patching_rect" : [ 740.0, 270.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-ratio4", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "float" ], "text" : "* 2.30", "patching_rect" : [ 800.0, 270.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-ratio5", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "float" ], "text" : "* 2.65", "patching_rect" : [ 860.0, 270.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-reson1", "maxclass" : "newobj", "numinlets" : 3, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "reson~ 1 100 14", "patching_rect" : [ 620.0, 320.0, 100.0, 22.0 ] } },
			{ "box" : { "id" : "obj-reson2", "maxclass" : "newobj", "numinlets" : 3, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "reson~ 1 160 10", "patching_rect" : [ 680.0, 320.0, 100.0, 22.0 ] } },
			{ "box" : { "id" : "obj-reson3", "maxclass" : "newobj", "numinlets" : 3, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "reson~ 0.8 215 8", "patching_rect" : [ 740.0, 320.0, 100.0, 22.0 ] } },
			{ "box" : { "id" : "obj-reson4", "maxclass" : "newobj", "numinlets" : 3, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "reson~ 0.7 230 6", "patching_rect" : [ 800.0, 320.0, 100.0, 22.0 ] } },
			{ "box" : { "id" : "obj-reson5", "maxclass" : "newobj", "numinlets" : 3, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "reson~ 0.6 265 4", "patching_rect" : [ 860.0, 320.0, 100.0, 22.0 ] } },
			{ "box" : { "id" : "obj-sum1", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "+~", "patching_rect" : [ 620.0, 380.0, 40.0, 22.0 ] } },
			{ "box" : { "id" : "obj-sum2", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "+~", "patching_rect" : [ 620.0, 430.0, 40.0, 22.0 ] } },
			{ "box" : { "id" : "obj-sum3", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "+~", "patching_rect" : [ 620.0, 480.0, 40.0, 22.0 ] } },
			{ "box" : { "id" : "obj-sum4", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "+~", "patching_rect" : [ 620.0, 530.0, 40.0, 22.0 ] } },
			{ "box" : { "id" : "obj-modalgain", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "*~ 0.5", "patching_rect" : [ 620.0, 580.0, 60.0, 22.0 ] } },
			{ "box" : { "id" : "obj-ms1", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "+~", "patching_rect" : [ 160.0, 580.0, 40.0, 22.0 ] } },
			{ "box" : { "id" : "obj-ms2", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "+~", "patching_rect" : [ 160.0, 630.0, 40.0, 22.0 ] } },
			{ "box" : { "id" : "obj-mastergain", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 1,
				"outlettype" : [ "signal" ], "text" : "*~ 0.8", "patching_rect" : [ 160.0, 680.0, 60.0, 22.0 ] } },
			{ "box" : { "id" : "obj-dac", "maxclass" : "newobj", "numinlets" : 2, "numoutlets" : 0,
				"text" : "dac~ 1 2", "patching_rect" : [ 160.0, 730.0, 60.0, 22.0 ] } },
			{ "box" : { "id" : "obj-env", "maxclass" : "newobj", "numinlets" : 1, "numoutlets" : 1,
				"outlettype" : [ "" ], "text" : "env~", "patching_rect" : [ 320.0, 580.0, 50.0, 22.0 ] } },
			{ "box" : { "id" : "obj-rscale", "maxclass" : "newobj", "numinlets" : 5, "numoutlets" : 1,
				"outlettype" : [ "float" ], "text" : "scale -60. 0. 3.4 3.99", "patching_rect" : [ 320.0, 630.0, 150.0, 22.0 ] } },
			{ "box" : { "id" : "obj-rclip", "maxclass" : "newobj", "numinlets" : 3, "numoutlets" : 1,
				"outlettype" : [ "float" ], "text" : "clip 3.4 3.99", "patching_rect" : [ 320.0, 680.0, 90.0, 22.0 ] } },
			{ "box" : { "id" : "obj-rnum", "maxclass" : "flonum", "numinlets" : 1, "numoutlets" : 1,
				"outlettype" : [ "float" ], "patching_rect" : [ 430.0, 680.0, 60.0, 22.0 ] } }
		],
		"lines" : [
			{ "patchline" : { "source" : [ "obj-1", 0 ], "destination" : [ "obj-2", 0 ] } },
			{ "patchline" : { "source" : [ "obj-8", 0 ], "destination" : [ "obj-9", 0 ] } },
			{ "patchline" : { "source" : [ "obj-9", 0 ], "destination" : [ "obj-7", 1 ] } },
			{ "patchline" : { "source" : [ "obj-2", 0 ], "destination" : [ "obj-7", 0 ] } },
			{ "patchline" : { "source" : [ "obj-7", 0 ], "destination" : [ "obj-11", 0 ] } },
			{ "patchline" : { "source" : [ "obj-7", 0 ], "destination" : [ "obj-EXPR", 0 ] } },
			{ "patchline" : { "source" : [ "obj-7", 0 ], "destination" : [ "obj-fscale", 0 ] } },
			{ "patchline" : { "source" : [ "obj-7", 0 ], "destination" : [ "obj-xnum", 0 ] } },
			{ "patchline" : { "source" : [ "obj-rclip", 0 ], "destination" : [ "obj-EXPR", 1 ] } },
			{ "patchline" : { "source" : [ "obj-EXPR", 0 ], "destination" : [ "obj-7", 1 ] } },
			{ "patchline" : { "source" : [ "obj-11", 0 ], "destination" : [ "obj-12", 0 ] } },
			{ "patchline" : { "source" : [ "obj-12", 0 ], "destination" : [ "obj-fhold", 0 ] } },
			{ "patchline" : { "source" : [ "obj-12", 0 ], "destination" : [ "obj-13", 0 ] } },
			{ "patchline" : { "source" : [ "obj-fscale", 0 ], "destination" : [ "obj-fhold", 1 ] } },
			{ "patchline" : { "source" : [ "obj-fhold", 0 ], "destination" : [ "obj-fhtf", 0 ] } },
			{ "patchline" : { "source" : [ "obj-fhtf", 1 ], "destination" : [ "obj-pitchcurve", 0 ] } },
			{ "patchline" : { "source" : [ "obj-fhtf", 0 ], "destination" : [ "obj-mul03", 0 ] } },
			{ "patchline" : { "source" : [ "obj-mul03", 0 ], "destination" : [ "obj-packpitch", 0 ] } },
			{ "patchline" : { "source" : [ "obj-packpitch", 0 ], "destination" : [ "obj-pitchcurve", 0 ] } },
			{ "patchline" : { "source" : [ "obj-pitchcurve", 0 ], "destination" : [ "obj-fundcycle", 0 ] } },
			{ "patchline" : { "source" : [ "obj-13", 2 ], "destination" : [ "obj-phasereset", 0 ] } },
			{ "patchline" : { "source" : [ "obj-phasereset", 0 ], "destination" : [ "obj-fundcycle", 1 ] } },
			{ "patchline" : { "source" : [ "obj-13", 1 ], "destination" : [ "obj-ampmsg", 0 ] } },
			{ "patchline" : { "source" : [ "obj-ampmsg", 0 ], "destination" : [ "obj-ampcurve", 0 ] } },
			{ "patchline" : { "source" : [ "obj-ampcurve", 0 ], "destination" : [ "obj-fundmult", 1 ] } },
			{ "patchline" : { "source" : [ "obj-fundcycle", 0 ], "destination" : [ "obj-fundmult", 0 ] } },
			{ "patchline" : { "source" : [ "obj-13", 0 ], "destination" : [ "obj-clickmsg", 0 ] } },
			{ "patchline" : { "source" : [ "obj-clickmsg", 0 ], "destination" : [ "obj-clickenv", 0 ] } },
			{ "patchline" : { "source" : [ "obj-noise", 0 ], "destination" : [ "obj-impulse", 0 ] } },
			{ "patchline" : { "source" : [ "obj-clickenv", 0 ], "destination" : [ "obj-impulse", 1 ] } },
			{ "patchline" : { "source" : [ "obj-impulse", 0 ], "destination" : [ "obj-beaterfilt", 0 ] } },
			{ "patchline" : { "source" : [ "obj-beaterfilt", 0 ], "destination" : [ "obj-beatergain", 0 ] } },
			{ "patchline" : { "source" : [ "obj-fhold", 0 ], "destination" : [ "obj-ratio1", 0 ] } },
			{ "patchline" : { "source" : [ "obj-fhold", 0 ], "destination" : [ "obj-ratio2", 0 ] } },
			{ "patchline" : { "source" : [ "obj-fhold", 0 ], "destination" : [ "obj-ratio3", 0 ] } },
			{ "patchline" : { "source" : [ "obj-fhold", 0 ], "destination" : [ "obj-ratio4", 0 ] } },
			{ "patchline" : { "source" : [ "obj-fhold", 0 ], "destination" : [ "obj-ratio5", 0 ] } },
			{ "patchline" : { "source" : [ "obj-impulse", 0 ], "destination" : [ "obj-reson1", 0 ] } },
			{ "patchline" : { "source" : [ "obj-impulse", 0 ], "destination" : [ "obj-reson2", 0 ] } },
			{ "patchline" : { "source" : [ "obj-impulse", 0 ], "destination" : [ "obj-reson3", 0 ] } },
			{ "patchline" : { "source" : [ "obj-impulse", 0 ], "destination" : [ "obj-reson4", 0 ] } },
			{ "patchline" : { "source" : [ "obj-impulse", 0 ], "destination" : [ "obj-reson5", 0 ] } },
			{ "patchline" : { "source" : [ "obj-ratio1", 0 ], "destination" : [ "obj-reson1", 1 ] } },
			{ "patchline" : { "source" : [ "obj-ratio2", 0 ], "destination" : [ "obj-reson2", 1 ] } },
			{ "patchline" : { "source" : [ "obj-ratio3", 0 ], "destination" : [ "obj-reson3", 1 ] } },
			{ "patchline" : { "source" : [ "obj-ratio4", 0 ], "destination" : [ "obj-reson4", 1 ] } },
			{ "patchline" : { "source" : [ "obj-ratio5", 0 ], "destination" : [ "obj-reson5", 1 ] } },
			{ "patchline" : { "source" : [ "obj-reson1", 0 ], "destination" : [ "obj-sum1", 0 ] } },
			{ "patchline" : { "source" : [ "obj-reson2", 0 ], "destination" : [ "obj-sum1", 1 ] } },
			{ "patchline" : { "source" : [ "obj-sum1", 0 ], "destination" : [ "obj-sum2", 0 ] } },
			{ "patchline" : { "source" : [ "obj-reson3", 0 ], "destination" : [ "obj-sum2", 1 ] } },
			{ "patchline" : { "source" : [ "obj-sum2", 0 ], "destination" : [ "obj-sum3", 0 ] } },
			{ "patchline" : { "source" : [ "obj-reson4", 0 ], "destination" : [ "obj-sum3", 1 ] } },
			{ "patchline" : { "source" : [ "obj-sum3", 0 ], "destination" : [ "obj-sum4", 0 ] } },
			{ "patchline" : { "source" : [ "obj-reson5", 0 ], "destination" : [ "obj-sum4", 1 ] } },
			{ "patchline" : { "source" : [ "obj-sum4", 0 ], "destination" : [ "obj-modalgain", 0 ] } },
			{ "patchline" : { "source" : [ "obj-fundmult", 0 ], "destination" : [ "obj-ms1", 0 ] } },
			{ "patchline" : { "source" : [ "obj-modalgain", 0 ], "destination" : [ "obj-ms1", 1 ] } },
			{ "patchline" : { "source" : [ "obj-ms1", 0 ], "destination" : [ "obj-ms2", 0 ] } },
			{ "patchline" : { "source" : [ "obj-beatergain", 0 ], "destination" : [ "obj-ms2", 1 ] } },
			{ "patchline" : { "source" : [ "obj-ms2", 0 ], "destination" : [ "obj-mastergain", 0 ] } },
			{ "patchline" : { "source" : [ "obj-mastergain", 0 ], "destination" : [ "obj-dac", 0 ] } },
			{ "patchline" : { "source" : [ "obj-mastergain", 0 ], "destination" : [ "obj-dac", 1 ] } },
			{ "patchline" : { "source" : [ "obj-mastergain", 0 ], "destination" : [ "obj-env", 0 ] } },
			{ "patchline" : { "source" : [ "obj-env", 0 ], "destination" : [ "obj-rscale", 0 ] } },
			{ "patchline" : { "source" : [ "obj-rscale", 0 ], "destination" : [ "obj-rclip", 0 ] } },
			{ "patchline" : { "source" : [ "obj-rclip", 0 ], "destination" : [ "obj-rnum", 0 ] } }
		]
	}
}
